#!/usr/bin/env python3
"""Build the full run-up calendar: 122 daily posts, Aug -> the November event.

Day 122 = event day. The calendar is countdown-relative, so it shifts to whatever
November date the show lands on.

  days 1–7     the offer          (the original opening week)
  days 8–99    the serial         (92 posts, seven recurring formats)
  days 100–122 the countdown      (the original crews/people/games run)
"""
import json
from collections import OrderedDict as O

SRC = '/home/user/showbuilderapp/marketing/daily-transmissions.json'
OUT = SRC
old = json.load(open(SRC))
OLD = {p['day']: p for p in old['posts']}

G, P, C, V, L, S, N = '#f5c542', '#ff2d9b', '#00e5ff', '#a06bff', '#ff5a6e', '#ffd36b', '#8f8fa6'

FORMATS = O([
 ("TRANSMISSION", "TJ straight to camera about the night itself. The offer, the ask, the stakes. The only format that sells."),
 ("CITY RECORDS", "A piece of the fifty-year history. TJ over archive-feel b-roll — no face needed, batch the VO."),
 ("RAP SHEET",    "One character, one file. Name, crew, known for, one story. The most batchable format you have."),
 ("OVERHEARD",    "One line somebody said, then TJ explains what it meant. Shortest format, highest share rate."),
 ("THE DIAL",     "The music. What each crew sounds like and why. Your natural territory — shoot these behind the decks."),
 ("EVIDENCE",     "McGraw's case. A photo, a file, a dead end. This is the format that carries the myth."),
 ("HOUSE RULES",  "Practical. What the night is, what to wear, how it works. Kills objections and drives tickets."),
])

# day, format, title, hook, onScreen, script, shotA, shotB, caption, cta, share, colour
NEW = [
# ---------------- AUGUST · THE CITY (8–31) ----------------
(8,"CITY RECORDS","Four Towns","This was never one city. It was four towns that grew until they touched.","FOUR TOWNS. ONE MAP.",
 "This was never one city.\nIt was four towns — the docks, the marina, the block and the flats — and they grew until they touched, and then they kept growing.\nBy the time anybody drew a single line around all four and gave it one name, the families were already in place.\nSo when people ask me who runs this city, that's the wrong question too.\nNobody runs it. Four people run a quarter each, and they've spent fifty years pretending that's the same thing.",
 "aerial over four glowing districts, night","an old map, four hand-drawn borders",
 "It was four towns before it was one city. That never really stopped.","Which quarter are you from?","Local-identity hook — people map it onto their own city.",N),
(9,"RAP SHEET","The Gold Docks","The oldest money in this city still smells like fish and diesel.","DISTRICT ONE — GOLD.",
 "The docks came first.\nOld stone, wet cobbles, bistro lights strung between buildings that were warehouses before they were restaurants.\nThe oldest money in this city still smells faintly of fish and diesel, and the people who have it would rather you didn't mention that.\nThis is Corvetti ground. Has been for three generations.\nYou'll know when you're on it, because everybody gets quieter.",
 "gold-lit waterfront, wet cobbles, harbour fog","hanging bistro lights, slow push",
 "The oldest money here still smells like the docks.","Gold crew — this is yours.","District identity: gives the gold faction a home to claim.",G),
(10,"OVERHEARD","We Just Rent It","\"It's nobody's city, boy. We just rent it.\" That's the most honest thing anyone's said all year.","\"…FROM HIM.\"",
 "Overheard on the pier, from a man in his seventies, to a man half his age who'd just claimed the whole city was his.\n\"It's nobody's city, boy. We just rent it.\"\nAnd then he looked up. At one lit window, high above the water.\nAnd he said: from him.\nThat's the most honest thing anybody in this city has said all year, and the man who said it is the last person you'd expect to admit it.",
 "rain pier at night, two figures squaring off","one lit penthouse window, very high up",
 "\"It's nobody's city, boy. We just rent it. …From him.\"","Rent it from who?","Mystery + a quotable line — the two things that travel.",G),
(11,"THE DIAL","Four Stations","This city has four radio stations and every one of them belongs to somebody dangerous.","TUNE IN. PICK A SIDE.",
 "Four crews. Four stations.\nGold Standard Radio, AM 10.40 — nothing but the classics, nothing but respect.\nLa Onda, 98.6 — the loudest signal on the water.\nRadio Los Santos, 106 — the block, the beat and the bounce.\nAnd 88.8 The Firm, which does not take requests, because it plays what's optimal.\nOn the night, whichever crew is up, that's what the room sounds like.\nYou'll feel the station change before anybody tells you it has.",
 "a radio dial sweeping four colours","four crowd pockets under four colour washes",
 "Four crews. Four stations. You'll hear the city change hands.","Which station are you tuned to?","Music identity — the audience's real entry point.",N),
(12,"TRANSMISSION","What You're Actually Buying","People keep asking if it's a club night or a show. It's neither, and that's the point.","IT'S A HEIST. YOU'RE IN IT.",
 "People keep asking whether this is a club night or a show.\nIt's neither, and that's the whole point.\nThere's a film. There are four crews. There's a vault. And there are twelve games that the entire building plays at the same time, on their phones, on the floor.\nYou don't sit and watch it, and you don't just dance through it. You get recruited, you pick a colour, and by the end of the night you either opened that vault or you watched somebody else do it.\nThat's what you're buying.",
 "wide floor, hundreds of phones lit","screens above a packed crowd",
 "Not a club night. Not a show. You get recruited.","Save this for whoever keeps asking.","Answers the actual objection — saveable, so it gets sent.",C),
(13,"EVIDENCE","The Board","There's a detective in this city with a wall of photographs and one empty space in the middle.","ONE SPACE. STILL EMPTY.",
 "There's a detective in this city who's been on the same case for twenty years.\nHe's got a wall. Photographs, string, four columns — one for each crew — and every face on it he can name.\nExcept one space. Middle of the board. Empty.\nTwenty years and he has never once been able to put a photograph in it.\nHe knows the man exists because of the shape of the hole he leaves.\nThat's the whole case. That's what Dutch McGraw has.",
 "a corkboard, four columns, one gap","string and pins, macro, low light",
 "Twenty years. One empty space in the middle of the board.","Who goes in the gap?","Invites theorising — the comments write themselves.",L),
(14,"HOUSE RULES","What The Night Looks Like","You walk in, somebody hands you a colour, and you're in a gang. That's minute one.","MINUTE ONE: YOU'RE IN A GANG.",
 "Here's what actually happens.\nYou walk in. Before you get to the bar, somebody hands you a colour — gold, pink, cyan or violet — and that's your crew for the night.\nThe story plays on the screens between the music. Every so often it stops and somebody hands you a job, and every phone in the room lights up at once.\nYou play. Your colour scores. The board goes up.\nNo stage. No queue. No getting picked on.\nJust you, your phone, and three other crews you now have a problem with.",
 "a wristband going on at the door","a leaderboard flipping over, four colours",
 "Minute one, you're in a gang. That's how it starts.","Who are you bringing?","Removes fear, adds a plus-one prompt.",C),
(15,"CITY RECORDS","Off The Boats","The first Corvetti in this city arrived with a suitcase and a grudge.","1951.",
 "The first Corvetti arrived here with a suitcase and a grudge.\nHe took work on the docks because that's what there was, and inside four years he owned the part of the docks nobody was watching.\nHe never raised his voice, he never wrote anything down, and he never once asked for anything twice.\nHis grandson runs the family now the exact same way.\nThat's not tradition. In this city, that's a business model that has outlived three police commissioners.",
 "an old suitcase on wet stone","a warehouse door, gold light spilling",
 "A suitcase and a grudge. Three generations later they still don't write anything down.","Gold crew, stand up.","Origin myth — factions love a founding story.",G),
(16,"RAP SHEET","The Pink Marina","There's a district in this city you can see from three miles away. That's deliberate.","DISTRICT TWO — PINK.",
 "You can see the marina from three miles away. That is entirely deliberate.\nBlack yachts, palm trees, and a mirrored mansion up on the rise with the lights left on whether anybody's home or not.\nThis is Halcón ground. Nothing here is hidden, nothing here is understated, and nothing here is an accident.\nThe Corvettis think it's vulgar.\nThe Halcóns think being seen is the whole point of having anything.",
 "hot-pink neon marina, black yachts","a mirrored mansion glowing through rain",
 "You can see it from three miles out. On purpose.","Pink crew — make noise.","Direct rivalry bait at the gold faction.",P),
(17,"OVERHEARD","What's The Drop","A grown man asked his father what the drop was. In front of people.","NEVER ASK TWICE.",
 "A grown man asked his father, out loud, in front of other people, what the drop was.\nAnd his father — who has buried better men for less — put down a cannoli, looked at him for a long time, and said: respect.\nAnd also the drop.\nI want to be clear that this family is the most feared organisation in this city.\nAnd that man is next in line.",
 "a cannoli on a checkered cloth, macro","a sweating man in an open collar",
 "\"Pop… what's the drop?\" A question you ask exactly once.","Tag your Vinnie.","Family-tag comedy, the highest-travel format.",G),
(18,"THE DIAL","Gold Standard","This crew's entire sound is men in suits singing about women who left them.","AM 10.40.",
 "Gold Standard Radio. AM 10.40.\nThis is the Corvetti sound, and it hasn't changed since 1962. Rat-Pack swing. Crooners. Doo-wop. Big brass when things are going well and a single sad string section when they're not.\nIt's men in beautiful suits singing about women who left them, and underneath all of it there's something with teeth.\nThat's the trick of that whole family in one sound.\nIt's warm right up until it isn't.",
 "vinyl crackle, a turntable, warm gold light","an empty velvet back room, slow push",
 "Warm right up until it isn't. That's the whole family in one sound.","What's your gold-crew anthem?","Music request = comments, and you're a DJ. Free content.",G),
(19,"TRANSMISSION","Not Extras","You're not the audience at this thing. You're the labour.","FOUR CREWS. NOT ENOUGH HANDS.",
 "Let me be blunt about your role in this.\nYou're not the audience. Four crews are walking into that building and not one of them has enough people to do what they're planning.\nThey need hands. To hold a floor, run a job, move a package, crack a code against three other crews doing exactly the same thing.\nSo they recruit. Off the floor. From whoever turned up.\nYou're not extras in somebody else's night.\nYou're the reason it can happen at all.",
 "a crowded floor from above, four colour pockets","a hand taking a coloured band",
 "You're not the audience. You're the labour. #GTAD","Who are you bringing?","Flattery + purpose — makes people want a role.",C),
(20,"EVIDENCE","The Empty File","The richest crew in this city built a file on him. I've read it. It's empty.","NO NAME. NO PHOTO.",
 "The Firm builds a file on everybody. It's most of what they actually do.\nThey've got one on him.\nNo name. No photograph. No date of birth, no known associates, no last known address.\nWhat's in it is a list of things that happened that nobody can explain, going back further than anybody working there has been alive.\nThe most data-obsessed crew in this city has one folder with nothing in it.\nAnd they will not throw it away.",
 "a manila folder opening on nothing","violet monitor glow on an empty desk",
 "The most data-obsessed crew in the city has one empty file. And they keep it.","Theories.","Mystery — never explained, so it keeps circulating.",V),
(21,"HOUSE RULES","What To Wear","Dress like you're in one of the four crews. Nobody's checking, everybody's looking.","WEAR YOUR COLOUR.",
 "What to wear.\nGold if you want the old money look — a good jacket, something that gleams.\nPink if you plan to be seen from across the room, which is the entire Halcón philosophy.\nCyan if you're here to be comfortable and still outlast everybody.\nViolet if you own one very expensive black turtleneck and you've been waiting for a reason.\nNobody's on the door checking.\nBut I promise you, everybody in that room is looking.",
 "four outfits under four colour washes","a crowd, colour-blocked, wide",
 "Gold, pink, cyan or violet. Nobody's checking. Everybody's looking.","What are you wearing?","Outfit posts drive tagging and group planning.",P),
(22,"CITY RECORDS","The Block","One crew in this city never wanted more than the twelve streets they grew up on.","TWELVE STREETS.",
 "Every crew in this story wanted the whole city.\nExcept one.\nThe Street Kings have never made a move outside twelve streets, and those twelve streets are the only part of this city where people are genuinely, uncomplicatedly glad to see the crew that runs them.\nThe other three have never understood it. They keep waiting for the expansion.\nIt isn't coming.\nMarcus Wells worked out something the rest of them haven't: it's easier to hold something people want you to have.",
 "cyan-lit corner store, murals, wet asphalt","a lowrider parked, hydraulics settling",
 "Twelve streets. They never wanted more. That's why they still have them.","Cyan crew — where you at?","Underdog appeal; the easiest faction to root for.",C),
(23,"RAP SHEET","The Cyan Block","Nobody in this district got frightened into anything. That makes it the hardest one to take.","DISTRICT THREE — CYAN.",
 "The block.\nMurals, corner stores, hydraulics, and the best three minutes of music in any room the Street Kings walk into.\nHere's what makes it the hardest district in the city to move on: nobody here got frightened into anything.\nYou can lean on people who were coerced. You can buy people who were bought.\nYou can't do much with a neighbourhood that actually likes who runs it.\nThe other three crews have tried. It's the one thing all three of them have failed at.",
 "cyan-lit block at night, steam from a grate","a convoy of chrome pulling out",
 "You can't lean on a neighbourhood that likes who runs it.","Cyan.","Values-based identity — the crew you join to be a good guy.",C),
(24,"OVERHEARD","A Legendary Honda","Somebody suggested boosting the getaway car might be his origin story. It's a Honda.","\"…A *LEGENDARY* HONDA.\"",
 "Overheard on the block.\nOne member of a serious criminal organisation floating the idea that he personally should boost the getaway car — that it might, and I'm quoting, be his origin story.\nHis boss, without any real cruelty, pointed out that it's a Honda.\nAnd he said — and this is the part I keep thinking about —\nA legendary Honda.\nThat man is going to be at this event. He's going to be at all of them.",
 "a beat-up Honda under neon, hero angle","a man mid-laugh, cyan light, holding food",
 "\"…A *legendary* Honda.\"","Tag whoever this is in your group.","Pure comedy — the clip that escapes your following.",C),
(25,"THE DIAL","Radio Los Santos","This is the only station in the city that nobody argues about.","FM 106.0.",
 "Radio Los Santos, 106.\nThe block, the beat and the bounce. G-funk, lowrider oldies, Chicano soul, talkbox, and the coolest groove in any building it gets played in.\nHere's the thing about the cyan station.\nEvery other crew in this city will tell you their sound is the best one. And every one of them, privately, likes this station.\nIt's the only signal in this city nobody argues about.\nWhen it drops, the whole room agrees for about four minutes.",
 "a lowrider on hydraulics, cyan glow","a packed floor moving as one, wide",
 "The only station in this city nobody argues about.","Name one that belongs on it.","Music tribalism + request bait.",C),
(26,"TRANSMISSION","Pick Early","You'll pick a colour at the door. I'd think about it before then.","AT THE DOOR IT'S FINAL.",
 "You get one choice at that door and you're stuck with it all night.\nGold, if you think power should be quiet.\nPink, if you have never once been the quietest person in a room.\nCyan, if your friends actually like you.\nViolet, if you've read the terms and conditions and found a way through them.\nAnd before you tell me you'll decide when you get there — you won't. You'll pick whatever your mate picks, and then you'll spend the whole night defending it.\nSo think about it now.",
 "four wristbands on four wrists","a door with four coloured lights above it",
 "Gold, pink, cyan or violet. At the door it's final. #GTAD","Comment your colour. I'm counting.","THE identity post — repeatable monthly, always performs.",P),
(27,"EVIDENCE","The Photograph","There is one photograph of him in existence and you can't see him in it.","HE'S IN THIS PHOTO.",
 "There's one photograph.\nTaken outside a restaurant on the docks, nineteen years ago, by somebody who didn't know what they were taking a picture of.\nFour men at a table. Everybody in this city can name three of them.\nAnd at the edge of the frame, half out of shot, there's a hand. Black glove. Resting on the back of the fourth chair.\nThat's it. That's the only image anybody has.\nMcGraw has had it enlarged eleven times.",
 "an old photo, four men at a table, edge of frame","a black-gloved hand on a chair back, macro",
 "One photograph. Four men. And a hand on the fourth chair.","Zoom in. Tell me what you see.","Zoom-in bait — people literally screenshot and circle it.",N),
(28,"HOUSE RULES","Your Phone Is The Controller","No app to download at the door. If you can hold a phone, you're playing.","NOTHING TO DOWNLOAD.",
 "The most common question I get, so let's kill it.\nThere is nothing to download at the door. No app store, no queue, no signing up to anything, no handing over your email to play a game.\nYou'll get sent to a page. It'll load. That's the whole process.\nCharge your phone before you come, because you'll be on it more than you expect — and because I am not lending you mine.\nIf you can hold a phone and hear me, you're playing.",
 "a phone lighting up with a game card","a floor of raised phones, all glowing",
 "Nothing to download. Just charge your phone.","Send this to the one who always asks.","Objection-killer, highly saveable.",C),
(29,"CITY RECORDS","The Tower","In 2011 somebody bought their way into a fifty-year-old arrangement. Nobody has forgiven it.","THEY BOUGHT IN.",
 "Everybody else in this story inherited their place.\nThe Firm bought theirs.\nA glass tower went up on the flats, and inside eighteen months the people in it had a seat at a table that three families had spent fifty years dying for.\nThey didn't fight anybody. They didn't have to. They just made it more expensive to say no than to say yes.\nThe other three call them tourists.\nAnd every single one of the other three has taken their money.",
 "cold violet towers, one lit floor high up","a business card straightened, macro",
 "Three families died for that seat. The Firm bought it.","Violet crew, defend yourselves.","Villain faction — being hated is engagement.",V),
(30,"RAP SHEET","The Violet Towers","The newest district in this city has no history, and they've turned that into a selling point.","DISTRICT FOUR — VIOLET.",
 "The flats.\nCold glass, violet light, and a district with no history whatsoever — which The Firm has somehow turned into a selling point.\nNo old grudges. No inherited debts. No cousin you have to employ.\nThey'll tell you they're the only crew in this city operating without legacy drag, and the infuriating thing is that they're not entirely wrong.\nThey're the newest, richest, least liked crew in this story.\nAnd they're the only one that's grown every single year.",
 "a cluster of violet glass towers, rain","a monitor wall, screen glow, no faces",
 "No history. They've made that a selling point. And it's working.","Violet.","The faction people love to argue against.",V),
(31,"OVERHEARD","The Rat Is You","Somebody asked their analyst who was leaking. She answered honestly.","\"THE RAT IS YOU.\"",
 "A founder in this city ordered a full loyalty audit. Every crew, cross-referenced. He wanted to know if they could gamify it — whether the rat could be, and I'm quoting again, a subscription.\nHis analyst looked up exactly once and said: the rat is you. You post everything.\nThen went back to her tablet.\nShe is paid a fraction of what he is.\nShe is the only reason that tower is still standing.",
 "a tablet and a raised eyebrow, no full face","violet monitor glow, an empty founder's chair",
 "\"The rat is you, Preston. You post everything.\"","Tag the one holding your workplace together.","Workplace recognition — travels far outside nightlife.",V),

# ---------------- SEPTEMBER · THE FAMILIES (32–61) ----------------
(32,"THE DIAL","88.8 The Firm","This station doesn't take requests. It plays what's optimal.","\"TERMS APPLY.\"",
 "88.8 The Firm.\nGlossy eighties synth-pop, yacht rock, and then — without warning — cold techno with nothing human in it at all.\nIt is precise, expensive, and slightly soulless on purpose.\nTheir station ident says: we don't play requests, we play what's optimal. Crime, as a service. Terms apply.\nAnd here's what bothers me. It's the most technically well-made sound in this city.\nIt's just that nobody's ever cried to it.",
 "sterile violet room, one moving light","a mixer, cold light, precise hands",
 "\"We don't play requests. We play what's optimal.\"","Is it a banger or is it a spreadsheet?","Opinion bait — an argument with a clear side.",V),
(33,"TRANSMISSION","Fifty Years","Everything about this night was decided in a room in 1974 by four men who hated each other.","1974. FOUR SIGNATURES.",
 "Everything about this night — the vault, the keys, the fact that all four of them have to be in the same room — was decided fifty years ago by four men who could not stand each other.\nThey had a problem: they'd made more money together than any one of them could safely hold.\nSo they built somewhere to put it.\nAnd then they made absolutely certain that none of them could ever get it out alone.\nThey thought they were being careful.\nWhat they actually did was leave this to their grandchildren.",
 "an old document, four signatures","a vault door being installed, archive feel",
 "Four men who hated each other built this problem in 1974.","Follow — I'm telling the whole fifty years.","Serial promise — converts a scroller into a follower.",N),
(34,"EVIDENCE","The Signature","Three of the four signatures on that document belong to men we can name.","THREE OF FOUR.",
 "The document exists. McGraw has a copy — a bad one, third generation, but readable.\nFour signatures at the bottom.\nThree of them belong to men this city can name. Founders. Grandfathers. Two of them have streets named after them, which is its own kind of joke.\nThe fourth signature is a single letter.\nJust an H.\nAnd every expert McGraw has shown it to has told him the same thing: whoever wrote that had signed it that way their whole life.",
 "a signature line, macro, one letter","a photocopied document under a lamp",
 "Three names. And one letter. H.","What's the H?","The myth advances — this is the post people bookmark.",N),
(35,"HOUSE RULES","Is It A Rave Or A Show","It's a night out that happens to have a plot. You can ignore the plot. Most people don't.","BOTH. IT'S BOTH.",
 "Straight answer, because people keep asking.\nIt's a night out that happens to have a plot.\nThe music runs all night — that part is exactly what you'd expect from me. The story happens between the music, on the screens, in about a minute at a time.\nYou can ignore all of it and just dance. Genuinely. Nobody will bother you.\nBut I'll tell you what happens: about an hour in, your mate picks a colour, starts winning, and you get competitive.\nEverybody says they'll ignore it. Almost nobody does.",
 "a packed dancefloor, screens above","a group leaning into one phone, laughing",
 "It's a night out with a plot. You can ignore the plot. You won't.","Which one of you goes competitive first?","Group-dynamic prompt — tags friends automatically.",C),
(36,"CITY RECORDS","The Four Men","They met in the back of a restaurant that's still open. You can eat there.","IT'S STILL OPEN.",
 "They met in the back of a restaurant on the docks.\nA dockmaster who controlled what came off the boats. A woman who ran every bar on the waterfront and never once appears in the official version of this story. A man from the block who owned the only trucks. And one more.\nThey agreed to stop competing, and inside three years they were richer than the city government.\nThe restaurant is still there.\nYou can eat there. The back room's usually booked.",
 "a warm restaurant back room, empty","a checkered tablecloth and four chairs",
 "Four people. One back room. The restaurant's still open.","Would you sit at that table?","Real-world texture makes fiction feel local.",G),
(37,"RAP SHEET","The Woman Nobody Mentions","One of the four founders was a woman and three families have quietly written her out.","SHE OWNED THE WATERFRONT.",
 "One of the four was a woman.\nShe ran every bar on that waterfront, which meant she knew everything about everyone, which is a more valuable asset than trucks or docks and all four of them knew it.\nShe's in the photograph. She's on the document.\nAnd she is in almost none of the versions of this story the families tell now.\nWork out which crew has been quietly editing her out for fifty years, and you've learnt something real about them.\nI'll come back to her.",
 "an archive photo, a woman at a bar, back to camera","a bar mirror, gold light, no faces",
 "One of the four founders was a woman. Three families have edited her out.","Which crew do you think did it?","Injustice + a puzzle — extremely strong comment driver.",G),
(38,"OVERHEARD","Like Brothers","Two men agreed to split it fifty-fifty. Neither of them let go of the handshake.","\"LIKE *BROTHERS*.\"",
 "Two crews at a table. A fifty-fifty split, agreed — and I want to get the wording right here — like brothers.\nNeither man let go of the handshake first. It went on long enough that people looked away.\nAnd afterwards the older one leant over to his son and said: Cain and Abel were brothers.\nYou remember how that ended.\nThey are going to be in the same building in November.\nSo are you.",
 "two hands gripped, gold vs pink light","a warehouse half-lit gold, half pink",
 "\"Cain and Abel were brothers. You remember how that ended.\"","Who breaks first?","Prediction bait — people commit to an answer publicly.",P),
(39,"THE DIAL","What 1974 Sounded Like","The year all this started, the number one record in this city was about somebody leaving.","THE YEAR IT STARTED.",
 "The year those four signed that document, the biggest record in this city was a break-up song.\nI find that funnier than I should.\nWhen I score the fifty-years-ago material, that's the palette — warm, analogue, a bit of tape hiss, strings that mean it.\nAnd when we come back to now, the room gets its four stations back.\nYou'll hear the decades move.\nThat's the actual job on the night: I'm not playing a set, I'm playing a timeline.",
 "a reel-to-reel spinning, warm light","a 1970s radio, glowing dial",
 "I'm not playing a set that night. I'm playing a timeline.","What's your 1974?","DJ-craft content — respect from the music audience.",N),
(40,"TRANSMISSION","Why They Split It","They didn't split the key because they were fair. They split it because they were scared.","FOUR KEYS = FOUR HOSTAGES.",
 "People assume the four keys were about fairness. An equal share, one each, very civilised.\nIt wasn't that.\nEach of those four men was certain the other three would take the lot the second his back was turned — and each of them was right.\nSo they built a door that made betrayal physically impossible. Four turns, one minute, or nothing opens.\nThat vault isn't a bank.\nIt's four men holding each other hostage, in steel, for fifty years.",
 "four coloured key-turns, macro","a lock ring, four segments, glowing",
 "It's not a vault. It's four men holding each other hostage in steel.","Would you have signed it?","Reframe — a sentence people quote back.",S),
(41,"EVIDENCE","The Blueprint","The vault's design was never filed with the city. Somebody made sure of it.","NO PERMIT. NO RECORD.",
 "A vault that size needs permits. Excavation, structural, electrical — a paper trail six inches thick.\nMcGraw went looking for it.\nThere is no record that vault was ever built. No permit, no inspection, no contractor, no invoice. The building above it has full documentation going back to 1969, and underneath it, officially, there is soil.\nSomebody didn't just build it quietly.\nSomebody went back afterwards and removed it from the city's memory.",
 "a filing drawer, one gap in the folders","architectural plans, a blank section",
 "Officially, there is no vault. Officially, that's soil.","Who erases a building?","Conspiracy escalation — feeds the theory crowd.",N),
(42,"HOUSE RULES","Can I Come Alone","Yes. And you'll leave with a crew, because that's structurally what this night does.","YOU WON'T STAY ALONE.",
 "Can you come on your own?\nYes. And I'd say this is one of the few nights where it genuinely doesn't matter.\nThe second you pick a colour you're on a team with a few hundred strangers who want the same thing you do, and by the third game you'll be shouting at people you've never met.\nThat's not me being romantic about it. It's structural.\nThe whole night is built to turn a room of individuals into four crews.\nYou'll walk in alone. You won't stay that way.",
 "a single figure entering a colour-lit room","strangers reacting together, wide",
 "Come alone if you want. You won't stay alone.","Send this to someone who never goes out.","Inclusion — reaches the people your ads miss.",C),
(43,"CITY RECORDS","The Gold Key","The first family took the gold key and immediately did something nobody expected.","THEY NEVER USED IT.",
 "The Corvettis took the gold key in 1974 and did something none of the others expected.\nNothing.\nNo attempt, no approach, no quiet conversation about maybe getting three of the four together. Fifty years of absolute stillness.\nThe other families read that as weakness for about a decade.\nThen they worked out what it actually was.\nThe Corvettis are the only family that has never once given the other three a reason to move against them.\nThat's not passivity. That's the longest game anybody in this city has ever played.",
 "a gold key in a drawer, macro","a still gold-lit room, dust in light",
 "Fifty years. They never once tried. That's the strategy.","Patience or fear?","Debate prompt with two defensible sides.",G),
(44,"RAP SHEET","The Don At Thirty","Before he was the quietest man in the city, he was the loudest man in the room.","HE USED TO SHOUT.",
 "There's a version of Salvatore Corvetti most people have never heard about.\nAt thirty he was loud. Genuinely loud — a shouter, a table-thumper, the kind of man who settled things immediately and badly.\nThen in 1981 something happened that he has never discussed, and afterwards he never raised his voice again.\nNot once. Not in forty-plus years.\nEverybody in this city has a theory about 1981.\nNobody has ever asked him.",
 "an old photo of a young man, gold light","an elderly hand, a pinky ring, still",
 "In 1981 he stopped shouting. Nobody's ever found out why.","What happened in 1981?","An open loop you can pay off much later.",G),
(45,"OVERHEARD","Nothing Written Down","\"Nothing written down, nothing said twice.\" That's not caution. It's a whole worldview.","SAID ONCE. THAT'S IT.",
 "Overheard in a back room on the docks, from a man explaining to his son how the family works:\nNothing written down. Nothing said twice.\nPeople hear that and think it's about the police.\nIt isn't. Write it down and it can be taken. Say it twice and you've admitted the first time didn't land.\nThat family has run on those six words for three generations.\nAnd it's why the only crew in this city with no paper trail is also the only one that's never been raided.",
 "an empty notepad, gold light","a hand, a cigar, a still room",
 "\"Nothing written down. Nothing said twice.\"","Would you survive in that family?","A quotable rule — screenshot fodder.",G),
(46,"THE DIAL","Doo-Wop And Menace","There's a reason mob films use love songs over violence and it works on you every time.","WARM MUSIC. BAD ROOM.",
 "There's a trick every mob film uses and it works on you every single time.\nPut something warm over something terrible. A crooner, strings, three-part harmony — and underneath it, the worst night of somebody's life.\nYour ear says safe. Your eye says run.\nThat gap is where the whole gold station lives, and it's why I play it the way I do on the night.\nWhen you hear something beautiful in that room, check what's happening on the screens.",
 "a warm-lit room, one violent shadow","a record spinning, slow, close",
 "Warm music over a bad room. Works every time.","Name the best example.","Film-nerd bait — pulls a whole adjacent audience.",G),
(47,"TRANSMISSION","The Respect Economy","One crew in this city measures wealth in favours. It's the hardest currency there is.","MONEY IS JUST THE SCORE.",
 "The Corvettis don't really deal in money.\nThey deal in favours — given, owed, remembered — and money is just how they keep score afterwards.\nIt's the hardest currency in this city because you can't seize it, you can't trace it, and you can't stop owing it by paying.\nHalf the businesses on those docks think they're independent.\nThey're not. They just haven't been asked yet.\nOn the night, gold plays exactly like that. Quiet, patient, and then suddenly you owe them.",
 "a handshake in gold light, no faces","a restaurant, full tables, warm",
 "You can't seize a favour. That's why they still have everything.","Who do you still owe?","Uncomfortable-question format — high reply rate.",G),
(48,"EVIDENCE","The Receipt","McGraw found one receipt in twenty years. It's for flowers.","FLOWERS. EVERY YEAR.",
 "In twenty years, McGraw has found exactly one piece of paper connecting anybody to the fourth signature.\nA receipt. Annual, same date, same florist, going back further than the shop's own records.\nWhite flowers. Delivered to a grave with no name on it, in a plot that was paid for in cash in 1982.\nThat's it. That's his entire physical evidence.\nA man who doesn't exist has been sending flowers to somebody for forty years.\nMcGraw sits in that cemetery every year on that date.\nNobody's ever come.",
 "white flowers on an unmarked grave","a florist receipt, macro, aged",
 "A man who doesn't exist sends flowers to a grave with no name. Every year.","Who's in the grave?","Emotional mystery — the strongest myth post in the run.",N),
(49,"HOUSE RULES","Timings","Doors, story, games, and the part where the whole building loses it. In that order.","THE SHAPE OF THE NIGHT.",
 "The shape of the night.\nDoors open, you get your colour, and for the first while it's just a good room and good music while everybody arrives.\nThen the story starts, and from there it alternates — music, story, game, music — all night, and the games get bigger.\nThe last one is the vault, and that's the loudest the building gets all night, by a distance.\nThen we come down, we count it, and somebody's crew walks out having won the whole thing.\nCome early. The first game matters more than people think.",
 "a clock face, neon reflection","a room filling up, wide, colour-lit",
 "Come early. The first game matters more than people think.","What time are you getting there?","Practical + urgency; reduces late arrivals.",C),
(50,"CITY RECORDS","The Pink Key","The second key changed hands in 1987, violently, and the city pretended not to notice.","1987. IT CHANGED HANDS.",
 "The pink key didn't pass down. It was taken.\nIn 1987 the family that held it had a bad year — three funerals in five months, all officially unrelated — and by the spring somebody new was holding it and nobody asked how.\nThe city's official position was that nothing had happened.\nThe Halcóns have held it ever since, and they are the only crew whose claim rests on something everybody can remember.\nWhich is exactly why they're the loudest.\nYou don't have to shout when nobody doubts you.",
 "a pink-lit marina, 80s haze","a newspaper page, three obituaries",
 "The pink key wasn't inherited. It was taken. In 1987.","Does that make it theirs?","Moral argument — genuinely divides a comment section.",P),
(51,"RAP SHEET","Rico's Arrival","He came to this city with nothing and made sure everybody watched him get everything.","BE SEEN. THAT'S THE PLAN.",
 "Rico Delgado arrived here with nothing and made absolutely certain the whole city watched him acquire everything.\nThat's not vanity — or it's not only vanity.\nIf you come up quietly, people can pretend you're not there and take it back. If you come up loudly enough, taking it back means admitting they let it happen.\nHe made himself impossible to remove without embarrassment.\nThe white suit, the tiger, the mansion you can see from the bridge — all of it is armour.\nExpensive, ridiculous, and it has worked for twenty years.",
 "a white suit under pink neon","a mansion lit up, seen from a bridge",
 "The suit, the tiger, the mansion. It's not vanity. It's armour.","Genius or too much?","Reframes a joke into strategy — earns respect.",P),
(52,"OVERHEARD","Say Goodnight","Somebody shot at him in his own house. He didn't duck. He complained.","HE WASN'T SCARED.",
 "A round went past Rico Delgado's face, close enough to feel, in his own front room.\nHe didn't duck. He didn't move.\nHe turned to his tiger and said: you believe this, Sugar? After everything I do for this city?\nThen he looked back at the window and said the line he says.\nHe wasn't frightened. He was offended.\nThat's the difference between him and everybody else in this story, and it's going to matter in November.",
 "white suit, calm, tracer streaks past","a tiger on a white couch, unbothered",
 "\"You believe this, Sugar? After everything I do for this city?\"","Would you have ducked?","Character-defining + a direct question.",P),
(53,"THE DIAL","La Onda","This station is the reason your neighbours know when the party started.","FM 98.6.",
 "La Onda, 98.6.\nMiami synth, gated drums, sax that has no business being that confident, and then it drops into modern Latin and the room doubles.\nThis is the loudest, sweatiest station on the dial and it is completely unapologetic about it.\nEvery other crew's sound is trying to tell you something.\nThis one's just trying to make you move, and it's very rarely wrong.\nWhen the pink station comes up on the night, you'll know without looking.",
 "pink neon, palms, heat haze","a crowd, hands up, sweat, motion blur",
 "The loudest signal on the water. No apologies.","Your one La Onda record — go.","Request bait; builds your actual crate.",P),
(54,"TRANSMISSION","Loud Versus Quiet","Two crews have opposite theories about power and by November one of them is wrong.","QUIET vs LOUD.",
 "There are two theories about power in this city.\nThe Corvettis think it's quiet. Never explain, never repeat, let people work out on their own that they shouldn't.\nThe Halcóns think it's loud. Be so visible that moving against you is a public act.\nBoth have worked for decades.\nThey've never had to be tested against each other on the same night, in the same room, over the same thing.\nIn November, they will be.\nOne of those theories is about to be wrong.",
 "gold room and pink room, split frame","two bosses squaring off, colour-split",
 "Quiet power or loud power. One of them is about to be wrong.","Which theory are you?","Binary identity — instant, low-effort engagement.",P),
(55,"EVIDENCE","The Permit","There is a legal permit in this city for one privately owned tiger. It's real.","THE TIGER IS LEGAL.",
 "Here's something that isn't a rumour.\nThere's a permit on file for one privately owned big cat. Filed correctly. Renewed annually. Fees paid on time, every time, for nine years.\nOne crime family in this city has never filed an accurate tax return, has three open investigations, and has been raided twice.\nAnd their tiger paperwork is immaculate.\nMcGraw has read that permit more times than he'd like to admit, looking for a mistake.\nThere isn't one. It's the only clean document in this entire case.",
 "an official permit, stamped, macro","a tiger, calm, regal, unbothered",
 "Three open investigations. Immaculate tiger paperwork.","Explain this crew to me.","Absurd detail — the kind people read out loud.",P),
(56,"HOUSE RULES","Photos","Take photos. There's a booth. Your crew card is the flex.","YOU'RE MADE. PROVE IT.",
 "Take photos. Please.\nThere's a booth, it's branded, and it will make you look considerably more dangerous than you are.\nAnd you'll have a crew card on your phone all night with your member number on it — which, when you come back, still says how long you've been in.\nThat's the flex. Not that you went. That you were early.\nPost them. Tag them. I look at all of it.\nThe people in the photos from the first one are going to be insufferable about it for years, and honestly, they'll have earned it.",
 "a branded photo booth, neon","a crew card on a phone screen",
 "The people at the first one are going to be insufferable about it. Rightly.","Be early. That's the flex.","FOMO + status; drives first-event urgency.",C),
(57,"CITY RECORDS","The Cyan Key","The third key was given away, and that's never happened in this city before or since.","IT WAS A GIFT.",
 "The cyan key is the only one that was given.\nNot inherited, not taken, not bought. In 1974 the man from the block was handed it by the other three because they needed his trucks and they assumed he'd be the easiest to remove later.\nHe wasn't.\nThree generations on, his family still has it, and they're the only ones who've never had to defend it, because there's never been a version of this city where the block would let them lose it.\nThey got underestimated on day one.\nThey've been living off that ever since.",
 "a cyan-lit street corner, night","an old truck, chrome, archive feel",
 "They handed it over because they thought he'd be easy. Fifty years later.","Cyan crew.","Underdog vindication — the most satisfying arc there is.",C),
(58,"RAP SHEET","Big Deal","He got the name as a joke. Then he made everybody use it seriously.","THE NAME WAS AN INSULT.",
 "Marcus Wells got called Big Deal as an insult.\nHe was nineteen, he'd just refused to do something that everybody expected him to do, and somebody older said it across a room to get a laugh. It got the laugh.\nHe kept the name.\nUsed it on everything, said it about himself, never once acknowledged it had been a joke — and inside about four years everybody in this city was saying it with a straight face.\nThat's the whole man in one story.\nHe doesn't argue with you. He just outlasts you.",
 "a calm man leaning on a lowrider","a fresh fade, one gold chain, hard light",
 "The name was an insult. He kept it until everybody said it straight.","Cyan.","Origin story with a real lesson — highly saveable.",C),
(59,"OVERHEARD","We Never Had A Lookout","\"The lookout's asleep.\" There was no lookout. He'd eaten the nachos of a man who does not exist.","THERE WAS NO LOOKOUT.",
 "Four in the morning, an alley, a job about to happen.\nOne man reports that the lookout is asleep, the light's on a timer, and they're good to move.\nThen adds that he also ate the lookout's nachos.\nHis boss points out, patiently, that they never had a lookout.\nLong pause.\n\"…RIP the nachos, then.\"\nThese are the people you're going to be working for in November.",
 "a dim neon alley at 4am","a searchlight sweeping a wall",
 "\"We never *had* a lookout, Problem.\" \"…RIP the nachos, then.\"","Tag them. You know who.","Pure comedy — the highest-velocity post type in the run.",C),
(60,"THE DIAL","Double Nostalgia","Play the original, then the record that sampled it. The room recognises both and feels clever.","TWO ERAS. ONE RECORD.",
 "Here's a move I'll use all night and I'm telling you now so you can catch it.\nPlay the original. Let it land. Then drop the record that sampled it thirty years later.\nHalf the room knows one. Half knows the other. Both halves feel clever, and for about eight bars two generations of people are having the exact same night.\nThat's the whole cyan station in one trick.\nIt's also, if I'm honest, the reason I do this job.",
 "two records side by side, one older","a mixed-age crowd, all reacting at once",
 "Play the original. Then play what sampled it. Watch the room split and re-join.","Best sample flip of all time. Go.","DJ-craft + a music argument that never ends.",C),
(61,"TRANSMISSION","Joined, Not Recruited","Three crews take people. One crew has people turn up.","THEY VOLUNTEER.",
 "Three of the four crews in this story recruit the way you'd expect. Pressure, money, or a debt you didn't know you had.\nThe Street Kings have a waiting list.\nPeople turn up. From the block, from outside it, from families who'd rather they didn't. Nobody leans on anybody.\nThe other three find that genuinely confusing, and it's the single biggest advantage anybody in this story has.\nOn the night, cyan will be the easiest colour to pick and the hardest crew to beat.\nThose two facts are the same fact.",
 "a queue outside a cyan-lit door","a crowd, arms round shoulders, laughing",
 "Three crews take people. One has a waiting list.","Cyan crew, say it loud.","Faction recruitment with a genuine argument behind it.",C),

# ---------------- OCTOBER · THE HEAT (62–92) ----------------
(62,"EVIDENCE","Bought, Not Given","The fourth key was sold in 2011, and the paperwork is perfect, which is the suspicious part.","THE PAPERWORK IS PERFECT.",
 "The violet key changed hands in 2011 and — unlike everything else in this story — there's a complete paper trail.\nBill of sale. Transfer of interest. Signed, witnessed, filed, taxed.\nThat's the part McGraw can't get past.\nEvery other transaction in fifty years of this has been a handshake, a funeral or a threat.\nThis one has a receipt.\nEither The Firm are the only honest crew in this city.\nOr they wanted somebody, someday, to be able to prove it was legally theirs.",
 "a stamped legal document, violet light","a glass tower lobby, empty, cold",
 "Fifty years of handshakes. And one perfect receipt.","Why would you paper it?","Detective logic — invites the audience to reason.",V),
(63,"HOUSE RULES","Getting In","Accessible, seated areas, and nothing in the games needs you to move.","YOU CAN PLAY SITTING DOWN.",
 "A real answer for anybody who's been burned by an interactive night before.\nEverything on the night happens on your phone. Every game can be played sitting down, standing still, from a booth, from the back, from wherever you're comfortable.\nNothing requires you to get to a stage, race anybody physically, or be quick on your feet.\nThere's seating, there's step-free access, and the screens are placed so you can follow the story from anywhere in the room.\nIf you want to play hard and not move much, this is genuinely the format for it.",
 "a seated group playing on phones","screens visible from the back of a room",
 "Every game can be played sitting down. That's by design.","Send this to whoever needs to know.","Access post — earns real goodwill and reaches carers.",C),
(64,"CITY RECORDS","The Buy-In","In 2011 somebody offered a family more money than the family was worth.","THEY SAID YES.",
 "In 2011, the family holding the fourth key got an offer.\nNot a threat. An offer — more money than the entire family was worth, in cash, immediately, with no conditions except one.\nThey said yes.\nAnd everybody in this city has spent thirteen years arguing about whether that was cowardice or the single smartest decision anybody in this story has ever made.\nThey're out. They're rich. Nobody's looking for them.\nMeanwhile the other three are about to walk into a building in November and risk everything.",
 "a briefcase of cash, violet light","an empty family home, lights off",
 "They took the money and walked. Cowards or the only smart ones here?","Would you have sold?","Moral dilemma — the format that always fills comments.",V),
(65,"RAP SHEET","Preston","He's never stolen anything with his hands. He'd like you to know that's the innovation.","\"I'VE REINVENTED THEFT.\"",
 "Preston Ashford Sterling the Third has never personally taken anything.\nHe finds that important. He'll tell you it's the innovation — no masks, no guns, no risk, just a proprietary infiltration solution currently in private beta.\nWhat he's actually built is a company that can afford to be patient, and in this city that's genuinely more dangerous than a gun.\nHe is also, and I cannot stress this enough, extremely annoying.\nBoth of those things are true and the second one is why people underestimate him.",
 "a black turtleneck, violet server glow","a phone in hand, over-lit face, close",
 "\"No masks. No guns. A proprietary infiltration solution.\"","Every industry has one. Name yours.","Recognition comedy with a real point underneath.",V),
(66,"OVERHEARD","Legacy Infrastructure","Three crime families were described, in a meeting, as legacy infrastructure.","HE SAID IT OUT LOUD.",
 "In a meeting, on a slide, a man referred to three multi-generational crime families as legacy infrastructure.\nOut loud. To their faces. With a laser pointer.\nAnd the worst part — the genuinely unforgivable part — is that they didn't have a response, because on that particular metric he wasn't wrong.\nThey've hated him ever since, and none of them can articulate why in a way that doesn't prove his point.\nThat's The Firm's whole method.\nBe insufferable, be correct, survive.",
 "a slide deck in a dark room, violet","three unimpressed silhouettes at a table",
 "He called three crime families \"legacy infrastructure\". With a laser pointer.","Villain or just early?","Contrarian bait — the reply guys arrive immediately.",V),
(67,"THE DIAL","Cold Rooms","Some music is built to make a room feel expensive and slightly unwelcome.","TOO CLEAN. ON PURPOSE.",
 "There's a kind of record that makes a room feel expensive and slightly unwelcoming at the same time.\nToo clean. Too precise. Nothing in it that sounds like a person.\nThat's the violet sound and I mix it deliberately cold on the night, because it's the only station on that dial that isn't trying to be your friend.\nAnd here's the uncomfortable bit — it's the one people dance hardest to at four in the morning.\nSay what you like about The Firm.\nThey understand exactly what you want when you stop pretending.",
 "a sterile room, one cold moving light","a late crowd, precise, hypnotic",
 "The only station on the dial not trying to be your friend.","Cold techno at 4am — yes or no?","Music opinion with a built-in argument.",V),
(68,"TRANSMISSION","The Keys Are Moving","For the first time in fifty years, all four keys have left the buildings they were kept in.","ALL FOUR. MOVING.",
 "Something changed this month.\nFor fifty years those four keys sat in four different places and never moved. Safety deposit, floor safe, wall, whatever each family does.\nAll four of them have moved.\nNot at once. Over about nine days, quietly, and every family thinks their move went unnoticed.\nNone of them did.\nWhich means all four crews now believe the same thing at the same time — that this is finally happening — and every one of them thinks they're the only one who knows.\nNovember.",
 "four safes, four hands, four colours","a black car pulling away, wet street",
 "All four keys moved this month. Every crew thinks they were the only one.","It's happening.","Plot escalation — signals the campaign is going somewhere.",S),
(69,"EVIDENCE","The Lead","After twenty years, McGraw got something. He's been sitting on it for a week.","HE HASN'T TOLD ANYONE.",
 "McGraw got something.\nI don't know what. I know he's had it for eight days, I know he hasn't filed it, and I know he hasn't told the one person at that precinct he actually trusts.\nHe's been to that cemetery twice this week. Off-duty. Both times in the rain.\nTwenty years of nothing and now he's sitting on something on his own, which tells you it's either the biggest thing he's ever had —\nor it's something he doesn't want to be true.\nWith McGraw it's usually both.",
 "a detective alone in a parked car, rain","an unmarked grave, wet flowers",
 "Twenty years of nothing. Now he's sitting on something and hasn't told anyone.","What did he find?","Cliffhanger on the audience's favourite character.",L),
(70,"HOUSE RULES","Tickets","Tickets are up. First one's in November and there is exactly one of it.","ONE NIGHT. ONE ROOM.",
 "Tickets are up.\nOne night, November, one room, and I'm going to be honest with you about capacity: this format only works at a certain size. Too few and the games don't roar. Too many and nobody can see the screens.\nSo there's a number, and when it's gone it's gone, and I'd rather tell you that now than do the countdown thing at you later.\nIf you've been following this since the docks and the four signatures —\nyou already know more about that room than most people who'll be standing in it.\nCome and use it.",
 "a ticket link on a phone, neon","doors closing on a lit room",
 "Tickets up. One night, one room, one number.","Link in bio.","Rewards the long-time follower — converts the serial.",S),
(71,"CITY RECORDS","The Last Time","All four families were in one room once before. Nine people went in and it ended in under four minutes.","IT LASTED 4 MINUTES.",
 "All four families have only been in one room together once since 1974.\nNineteen ninety-eight. A funeral. Neutral ground, everybody armed, everybody behaving.\nIt lasted under four minutes.\nNobody has ever said what was said. Three of the four people who spoke are dead now, and the fourth doesn't discuss it.\nWhat's on record is that all four families left by different doors and none of them have been in the same building since.\nUntil November.\nWhen they'll all be in one, on purpose, with you.",
 "an old church, four black cars outside","four doors, four exits, archive feel",
 "Last time all four were in a room it lasted four minutes.","What was said?","History + dread — builds real anticipation for the event.",N),
(72,"RAP SHEET","Dutch McGraw","Twenty years, no arrests, and he's the only person in this story I actually like.","0 ARRESTS. STILL HERE.",
 "Detective Dutch McGraw. Twenty years on one case, zero arrests, one trench coat.\nHe's been passed over four times. He's been told to drop it twice, formally, in writing. His wife left, partly over this. He keeps a toothpick in his mouth because he stopped smoking the week he took the case and never quite stopped needing something.\nHe is the only genuinely honest person in this entire story.\nAnd it has cost him absolutely everything.\nI hope he gets it. I don't think he will.",
 "a rumpled detective, red-blue light","an old case file, dog-eared, thick",
 "Zero arrests in twenty years. The only honest man here.","Does he ever get him?","Empathy — this is the character people get attached to.",L),
(73,"OVERHEARD","Twenty Years","\"Twenty years I've been asking the wrong questions to the wrong guys.\"","\"NOT TONIGHT.\"",
 "Overheard in a lineup room, from a man who has said the same thing to himself every year for two decades:\nTwenty years I've been asking the wrong questions to the wrong guys.\nAnd then, quieter — not tonight.\nHe says it every time. He's said it in front of five suspects, four of whom were in crews and one of whom had wandered in off a dance floor and was holding his booking number upside down.\nHe pointed at that one.\nHe always points at the wrong one.",
 "a lineup wall in silhouette","a toothpick jabbed toward the lens",
 "\"Twenty years asking the wrong questions.\" He says it every time.","Is this the year?","Sympathy + prediction; short and quotable.",L),
(74,"THE DIAL","The Scanner","There's a fifth signal on that dial and it isn't music.","IT'S NOT A STATION.",
 "There's a fifth signal on the dial and it isn't music.\nScanner chatter, siren stabs, and dispatch static — and on the night I use it as a texture, not a track. When the heat goes up in the story, it bleeds into whatever's playing and the room feels it before anybody's told them anything.\nThat's the point of scoring a night like this rather than just playing it.\nYou'll never consciously notice the scanner.\nYou'll just get tense, and not know why.",
 "a police scanner, red-blue light","blinds, siren light sweeping a wall",
 "There's a fifth signal on that dial. It's not music.","Ever noticed a DJ making you nervous on purpose?","Craft reveal — makes the audience feel let in.",L),
(75,"TRANSMISSION","The Gala","The President just announced a gala. Guess which building.","GUESS WHICH BUILDING.",
 "It's official. There's going to be a gala.\nA night of unity, he's calling it. A city standing together against crime. Podium, banner, applause, the lot.\nAnd it's in the building.\nThe same building. The one with the thing underneath it that nobody has permits for.\nEvery crew in this city got an invitation this week, and every crew knows the other three did too.\nSo now it's not a question of whether they'll all be in the same room.\nIt's a question of what they each think they're walking into.",
 "a WAR ON CRIME banner going up","four invitations, four colours, macro",
 "A night of unity. In that building. Sure.","Coincidence?","The plot turn the whole serial has been building to.",S),
(76,"EVIDENCE","The Invitation","Four invitations went out. There's a fifth name on the list nobody can account for.","FIVE NAMES. FOUR CREWS.",
 "The guest list leaked. Of course it did — it's a political event, they always leak.\nFour crews. Four invitations. All accounted for.\nAnd one more name that nobody at that office can explain, that nobody remembers adding, that came through with no contact details and no RSVP required.\nOne letter.\nThe organisers assume it's a typo.\nMcGraw does not assume it's a typo.",
 "a guest list, one line highlighted","an empty chair at a set table",
 "Four crews. Five names on the list.","He's going.","The myth confirmed as present — huge escalation.",N),
(77,"HOUSE RULES","If You're Late","The story runs on a clock. Miss the first twenty minutes and you'll spend the night behind.","DON'T MISS THE OPEN.",
 "If you're late, you'll still have a great night. But I'd rather be straight with you.\nThe opening sets up who everybody is, and the first game is where your crew starts scoring. Miss it and you'll spend the rest of the night one step behind people who didn't.\nThere's no penalty. Nobody's going to make you feel bad.\nYou'll just be the person going \"wait, which one's the tiger guy\" at eleven o'clock, and your crew will not have patience for you.\nCome early. Get your colour. Get the open.",
 "doors opening, a lit foyer","a wristband, a phone, a drink",
 "Miss the open and you'll spend all night going \"which one's the tiger guy?\"","Who in your group is always late?","Group-callout — tags happen automatically.",C),
(78,"CITY RECORDS","The Donor List","The President's biggest donors are four organisations that officially don't exist.","FOUR DONORS. NO NAMES.",
 "The President's campaign filings are public, which is the funny thing about all of this.\nHis four largest donors are registered as consultancies. One's registered at a restaurant on the docks. One at a marina office that's been closed since 2019. One at a corner store. And one at a glass tower where the listed director is a man who has never been photographed at work.\nNone of this is hidden.\nIt's just filed correctly, and nobody reads filings.\nThat's the actual lesson of this whole story: the biggest things in this city are hiding in public.",
 "campaign filings, four highlighted lines","a podium, flags, TV lighting",
 "His four biggest donors are registered at a restaurant, a closed office, a corner store and a tower.","Nobody reads filings.","Satire that lands as real — travels beyond the audience.",S),
(79,"RAP SHEET","Diamante","He says he knows all the criminals personally. He means it as a qualification.","\"GREAT PEOPLE.\"",
 "President Maximillian Diamante will tell you nobody in this country is tougher on crime than he is, because he knows all the criminals personally.\nGreat people. Total winners.\nHe says it as a qualification. Like it's a CV line.\nAnd the genuinely upsetting thing is that it works — because it's true, and because saying it out loud is somehow more disarming than hiding it.\nHe's going to stand at a podium in November under a banner about a war on crime, with every criminal in this city holding a drink behind him.\nAnd he's going to get applause.",
 "a bombastic figure at a podium","four envelopes into a jacket, neck-down",
 "\"I know all the criminals personally. Great people. Total winners.\"","Four more years?","Political satire — the widest-reaching format here.",S),
(80,"OVERHEARD","Fine Patrons","He got to the word 'patrons' and had to pause, because four envelopes went in at once.","\"…PATRONS.\"",
 "At a rehearsal, reading from a script, a man practised the line: I have never, ever taken a dollar from any of these fine—\nAnd then stopped. Because in the actual room, at that exact moment, four envelopes in four different colours were going to be going into his jacket simultaneously.\nHe asked whether the timing could be adjusted.\nHe did not ask whether the envelopes could be.\nFour more years.",
 "a rehearsal, empty ballroom, one podium","gold, pink, cyan and violet envelopes",
 "He asked if the timing could be adjusted. Not the envelopes.","Four more years.","Satire with a punchline — the most shareable joke format.",S),
(81,"THE DIAL","State Broadcast","There's a sixth signal and it's brass, flags and absolutely nothing underneath.","POMP. NO CONTENT.",
 "The sixth signal on the dial is the State Broadcast, and it is entirely brass.\nCampaign-ad fanfare, national anthem energy, applause that isn't there.\nI use it for exactly one thing on the night: undercutting. It comes in over the top of something genuinely sinister and it makes the sinister thing funnier and worse at the same time.\nThat's the trick with satire in a room like that.\nDon't tell people it's ridiculous.\nPlay the fanfare and let them notice.",
 "flags, a podium, TV-broadcast light","a brass section, archive feel",
 "Don't tell people it's ridiculous. Play the fanfare and let them notice.","Best use of pomp in a film — go.","Craft + film argument; pulls the cinema crowd.",S),
(82,"TRANSMISSION","All Four Said Yes","Every crew RSVP'd within six hours of each other. None of them are going for the canapés.","ALL FOUR. SAME DAY.",
 "All four crews RSVP'd inside six hours of each other.\nThink about what that means. Four organisations who have not been in the same building since a funeral in 1998 all decided, on the same afternoon, that they were definitely attending a political fundraiser.\nNone of them are going for the canapés.\nAll four know the vault is under that room. All four are bringing a key. And all four have worked out that the other three will be doing exactly the same thing.\nThey're not sneaking in.\nThey're walking through the front door in black tie, and so are you.",
 "four RSVPs, four colours, macro","four black cars converging on one building",
 "Four crews. One building. Nobody's sneaking. Black tie.","Which door are you coming through?","The heist frame lands — this is the ticket-driver.",S),
(83,"EVIDENCE","Four Minutes","The vault's window is four minutes long, once a night, and only one person knows why.","FOUR MINUTES. ONCE.",
 "Here's what McGraw worked out that nobody else has.\nThat vault doesn't just need four keys. It needs them inside a window — and the window happens once a night, for about four minutes, when the building's systems cycle over.\nWhich means it isn't enough for all four crews to be there.\nThey have to all be there, together, ready, in the same four minutes, having agreed something.\nFour organisations who despise each other.\nCooperating precisely, on a clock, once.\nThat's the actual heist. Not the stealing. The agreeing.",
 "a building's systems cycling, lights dip","a clock face, four minutes marked",
 "The hard part isn't the stealing. It's four crews agreeing for four minutes.","Can they do it?","Reframes the whole story — the smartest post in the run.",N),
(84,"HOUSE RULES","Bringing People","Bring the friend who says they hate this kind of thing. They're the one who goes hardest.","BRING THE SCEPTIC.",
 "Bring the sceptic.\nEvery single time we run something like this, the person who said they weren't going to join in is on their feet by the third game, arguing with strangers about a colour they chose ninety minutes ago.\nIt's not because the games are irresistible. It's because being on a team is.\nThe ones who struggle are people who came expecting to sit and watch a show.\nThe ones who love it are people who came out for a good night and got handed a job.\nBring the second kind. Or bring the first kind and watch it happen.",
 "a group, one arms-folded, then not","a crowd all reacting at once",
 "Bring the friend who says they hate this stuff. They go hardest. Every time.","Tag your sceptic.","Direct tag mechanic with a promise attached.",C),
(85,"CITY RECORDS","The Weakness","Every vault has a weakness. This one's is that it was designed by people who didn't trust each other.","THE FLAW IS THE DESIGN.",
 "Every vault has a weakness, and this one's isn't the steel.\nIt's that four frightened men designed it.\nThey were so focused on making sure none of them could rob the others that they built something none of them could ever use. Fifty years of eight figures sitting under a building, earning nothing, helping nobody, because the safeguard worked perfectly.\nThat's the thing about that door.\nIt has never once failed.\nAnd it has never once let anybody in.",
 "a vault door, seams, one hard light","an empty concrete chamber, distant",
 "It's never failed. It's also never let anybody in. That's the flaw.","Perfect security or a perfect waste?","Philosophical hook — surprisingly strong on longer platforms.",N),
(86,"RAP SHEET","Sugar","She has stolen more from this city's crime families than any human being in this story.","THE TIGER IS WINNING.",
 "Let's talk about the tiger properly.\nSugar has been present at three of the most consequential meetings in this city in the last decade. She has never been searched, never been questioned, and has never once been considered a participant.\nDuring a fifty-fifty summit between the two most dangerous men in this city, she picked a bag of money off the table and walked out with it.\nNeither of them has noticed.\nBy weight, that tiger has stolen more from this city's crime families than anybody in this story.\nAnd she is the only one who is definitely going to get away with it.",
 "a tiger padding out of frame with a gold bag","an empty spot on a table where a bag was",
 "By weight, the tiger has stolen more than anyone in this story.","Send this to someone who'd get away with it.","The single highest-velocity post in the campaign.",P),
(87,"OVERHEARD","Don't Leave A Dollar","Two bosses said the same four words at the same time and neither enjoyed it.","\"DON'T LEAVE A DOLLAR.\"",
 "Two men who cannot stand each other, briefing a job together, arrived at the end of the same sentence at the same moment.\nDon't leave a dollar.\nThey said it in unison. Then they looked at each other with real hatred, because agreeing had felt good and neither of them was ready for that.\nThat's the thing about November.\nThey're going to have to cooperate.\nAnd the worst part, for them, is that they might enjoy it.",
 "two bosses, gold and pink light, mid-brief","a smashed neon window, loot falling",
 "They said it in unison. Then hated each other for it.","Enemies-to-allies. Called it.","Ships the rivalry — audiences adore this dynamic.",P),
(88,"THE DIAL","Blending Turf","When two crews work together, I blend their stations. You can hear the alliance.","YOU'LL HEAR IT HAPPEN.",
 "Here's something I'm properly excited about for the night.\nWhen two crews work together on screen, I blend their two stations. A swing vocal over a Miami synth. A G-funk beat under an old crooner.\nSo you don't just watch an alliance happen — you hear the turf mixing, in real time, in the room.\nAnd when the alliance breaks, so does the mix.\nThat's not a gimmick. That's the whole reason to do this live instead of just playing you a film.\nThe room is an instrument that night.",
 "two records, two colour washes, blending","a crowd under two colliding colours",
 "When they ally, I blend their stations. When it breaks, so does the mix.","This is why it's live.","Craft flex — justifies the ticket price without saying so.",N),
(89,"TRANSMISSION","One Month","One month out. If you've been here since the docks, you know more than most people in that room.","ONE MONTH.",
 "One month.\nIf you've been with this since the docks and the four signatures, you now know things that most of the people standing in that room won't.\nYou know why there are four keys. You know the window's four minutes. You know what the flowers mean, or at least you know they mean something.\nAll of that is going to be useful.\nBecause on the night, when everybody else is working out what's happening, you'll already be playing.\nOne month. Pick your colour.",
 "a calendar, one date circled","a lit venue exterior, night, wet street",
 "One month. You already know more than most people who'll be in that room.","Colour. Now. In the comments.","Rewards long-term followers; makes lurkers commit.",S),
(90,"EVIDENCE","He's Been Here","McGraw found something in that cemetery. He's stopped going.","HE STOPPED GOING.",
 "McGraw's stopped going to the cemetery.\nHe went every year on that date for eleven years, sat in the rain, waited for somebody who never came.\nHe's stopped.\nNot because he gave up — I've never seen the man more awake than he's been this month. Because something about that grave stopped being a question.\nHe's got a name now. Or he's got half of one.\nAnd for the first time in twenty years, Dutch McGraw is not the one being led around this city.\nHe's ahead.",
 "an empty cemetery, wet flowers, no one","a detective walking away from a grave",
 "Eleven years he sat in that cemetery. This year he didn't go.","He's ahead. For the first time.","Pays off day 48 — long-arc payoff builds serial loyalty.",L),
(91,"HOUSE RULES","On The Night","What to actually expect, start to finish, no mystique.","NO MYSTIQUE. JUST FACTS.",
 "No mystique for one post. Just what happens.\nYou arrive, you get a colour, you get a link on your phone. There's music. About half an hour in, the story starts on the screens.\nFrom there it's music, story, game, music — twelve games across the night, all played on your phone, all scoring for your crew.\nThe last one is the vault and it's the loudest thing you'll do all year.\nThen we count it, somebody wins, and the music goes back up until they throw us out.\nThat's it. That's the night.",
 "a full run of the room, wide, colour-lit","a leaderboard, four colours climbing",
 "No mystique. That's the whole night, start to finish.","Any questions, ask below — I answer all of them.","Clarity converts; the Q&A replies become more content.",C),
(92,"CITY RECORDS","Fifty Years To The Day","The gala is fifty years to the week from the day four men signed that document.","THEY PICKED THE DATE.",
 "One last piece of history before we get into the night itself.\nThat gala, in November, falls fifty years almost to the week from the day those four men sat in a back room and signed a document that made all of this inevitable.\nThat could be a coincidence.\nThe President's office says it's a coincidence.\nBut somebody chose that date, and somebody added a fifth name to the guest list, and somebody has been sending white flowers to an unmarked grave every year for four decades.\nI don't think anything about November is a coincidence.\nI think somebody's been planning it for fifty years.",
 "an old document beside a new invitation","a calendar, two dates, fifty years apart",
 "Fifty years to the week. His office says coincidence.","It's not a coincidence.","Ties the whole serial together — the pre-countdown peak.",N),

# ---------------- EARLY NOVEMBER · FINAL APPROACH (93–99) ----------------
(93,"TRANSMISSION","Three Weeks","Three weeks. Everybody in this story is now doing something they can't undo.","NO MORE PREPARING.",
 "Three weeks.\nEverybody in this story has now done something they can't take back. Keys have moved. RSVPs are in. A detective has a name he won't say out loud.\nThere's no version of November where these four crews quietly decide not to bother.\nAnd there's no version where they manage it without people on the floor.\nSo here's where you come in, one more time, plainly.\nPick a colour. Get a ticket. Turn up early.\nThe rest of it I'll handle on the night.",
 "four cars on four wet streets","a venue exterior, lights coming on",
 "Three weeks. Nobody can call it off now.","Colour + ticket. That's the whole ask.","Urgency without a fake deadline.",S),
(94,"RAP SHEET","The Crews Are Moving","All four crews changed their behaviour this month. Here's how you'd spot it.","THEY'RE ALL MOVING.",
 "All four crews have changed behaviour this month and none of them think it's visible.\nThe Corvettis stopped taking meetings. The Halcóns started throwing parties, which for them is camouflage.\nThe Street Kings moved every car off the block.\nAnd The Firm filed three separate insurance policies in one week, which is the single most Firm thing that has ever happened.\nFour organisations preparing for the same night in four completely different languages.\nAll of them convinced they're the only one who's ready.",
 "four districts, four kinds of activity","a chess-like grid of four colours",
 "Four crews prepping in four different languages. All think they're alone.","Which crew's play is smartest?","Comparison prompt — factions argue their own corner.",N),
(95,"OVERHEARD","Last Words","\"If it goes wrong in there, get to the water.\" Somebody's already planning to lose.","SOMEBODY'S PLANNING TO LOSE.",
 "Overheard this week, from a senior man to somebody much younger:\nIf it goes wrong in there, don't go for a door. Get to the water.\nThink about what that tells you.\nSomebody in one of these four crews has already sat down and planned for the version where they don't get the money and they don't get out the front.\nThat's not pessimism. That's the most professional thing anybody's said in months.\nEverybody else is planning to win.\nOne of them is planning to survive.",
 "dark water at night, a distant boat","a fire exit, red light, wet floor",
 "\"If it goes wrong, get to the water.\" Somebody's planning to lose.","Which crew said it?","Dread + a guessing game — very high comment volume.",N),
(96,"THE DIAL","The Signal","There's one sound in this whole night that doesn't belong to any crew.","IT CUTS ACROSS ALL FOUR.",
 "There's one sound on that dial that doesn't belong to any crew.\nIt comes in over the top of whatever's playing — cuts across gold, pink, cyan and violet like none of them are there — and when it does, the room goes quiet without being asked.\nI've built it as a loop. Low, slow, a bit seductive, a bit wrong.\nYou'll hear it in the first ten minutes.\nYou'll hear it again at the very end.\nAnd what happens in between those two moments is the entire reason to be in that room.",
 "a radio dial warping between stations","a dark room, one low light, quiet crowd",
 "One sound that doesn't belong to any crew. You'll hear it twice.","What is it?","Musical mystery — a payoff people attend to receive.",N),
(97,"EVIDENCE","Last Chance","McGraw's been told to drop it. In writing. For the third time.","THIRD TIME. IN WRITING.",
 "McGraw's been told to drop it. Formally, in writing, third time in twenty years.\nHe's two years off a pension he's already been told won't be full.\nAnd he's going to be at that gala. Not officially — he's not on the list, he wasn't invited, and if he's recognised he'll be walked out and probably finished.\nHe's going anyway.\nEverybody else in that room is going for eight figures.\nHe's going for a name.\nOf every person walking into that building in November, he's the only one risking something he can't get back.",
 "a memo, stamped, on a cluttered desk","a lone figure outside a lit venue, rain",
 "Told to drop it. Third time. He's going anyway.","He deserves this one.","Rooting interest at peak — sets up the post-credit payoff.",L),
(98,"HOUSE RULES","Final Logistics","Doors, ID, phone charged, colour chosen. That's the whole checklist.","FOUR THINGS.",
 "Final checklist, then I'll stop being practical at you.\nBring ID. Charge your phone — properly, not to forty percent.\nGet there for doors, because the open sets up everything and the first game scores.\nAnd know your colour before you're standing at that desk with people behind you.\nThat's it. Four things.\nEverything else that night is handled — by me, from the booth, all night.\nYou just have to turn up ready to be somebody's soldier.",
 "a phone at 100%, neon reflection","a door, four coloured lights, queue",
 "ID. Charged phone. Doors. Colour. That's the list.","Screenshot this one.","Explicitly saveable — a checklist gets kept and re-shared.",C),
(99,"TRANSMISSION","From Here","From tomorrow I stop telling you history and start telling you who you're about to meet.","THE COUNTDOWN STARTS.",
 "From tomorrow this changes.\nI'm done with the history. Fifty years, four families, one document, one grave — you've got all of it, and it's going to matter more than you think.\nFrom here I'm introducing you to the people you're actually going to be in a room with. The four bosses. The ones standing behind them. The detective. The president.\nAnd then the games, one at a time, so you know exactly how to win them.\nThree weeks of that, and then doors.\nStay tuned in.",
 "a radio dial settling on one station","TJ to camera, hard key, black three-piece",
 "History's done. From tomorrow: who you're about to meet.","Don't tune out now.","Momentum handoff into the countdown run.",P),
]

# ---- assemble the 122-day calendar --------------------------------------------
def mk(day, fmt, title, hook, on, script, sa, sb, cap, cta, share, col):
    words = len(script.split())
    return O([("day", day), ("format", fmt), ("phase", phase_of(day)), ("title", title),
              ("colour", col), ("hook", hook), ("onScreenText", on), ("script", script),
              ("runtimeSec", round(words / 2.5)), ("words", words),
              ("shots", [sa, sb]), ("caption", cap), ("cta", cta), ("shareTrigger", share)])

def phase_of(d):
    if d <= 7:   return "Aug · the offer"
    if d <= 31:  return "Aug · the city"
    if d <= 61:  return "Sep · the families"
    if d <= 92:  return "Oct · the heat"
    if d <= 99:  return "Nov · final approach"
    return "Nov · the countdown"

posts = []
for d in range(1, 8):                        # the original opening week
    p = dict(OLD[d]); p['day'] = d; p['format'] = 'TRANSMISSION'; p['phase'] = phase_of(d)
    posts.append(O([(k, p[k]) for k in
        ("day","format","phase","title","colour","hook","onScreenText","script","runtimeSec","words",
         "shots","caption","cta","shareTrigger")]))
for row in NEW:
    posts.append(mk(*row))
for i, d in enumerate(range(8, 31)):          # the original countdown run
    p = dict(OLD[d]); p['day'] = 100 + i
    p['format'] = 'RAP SHEET' if p['phase'] in ('The Crews','The People') else 'TRANSMISSION'
    p['phase'] = phase_of(p['day'])
    posts.append(O([(k, p[k]) for k in
        ("day","format","phase","title","colour","hook","onScreenText","script","runtimeSec","words",
         "shots","caption","cta","shareTrigger")]))

doc = O([
 ("meta", O([
   ("name", "Grand Theft After-Dark — the run-up calendar"),
   ("what", "122 daily posts narrated by TJ, from launch to the first event. Day 122 is event day, so "
            "the calendar is countdown-relative — shift it to whatever November date the show lands on."),
   ("cadence", "7 a week until the first event. After that the tour starts and live footage takes over: "
               "drop to 3 a week (see tourCadence)."),
   ("phases", ["Days 1–7 · the offer — what this is, the vault, the four keys, why you",
               "Days 8–31 · the city — the four districts, the dial, the texture of the world",
               "Days 32–61 · the families — the fifty years that made this inevitable",
               "Days 62–92 · the heat — the keys move, the gala is announced, tickets go up",
               "Days 93–99 · final approach — three weeks out, everybody's committed",
               "Days 100–122 · the countdown — the crews, the people, the games, the ask"]),
   ("shootNote", "122 posts is not 122 shoots. Seven recurring formats means you batch: one lighting "
                 "setup, one wardrobe, twenty RAP SHEETs in an afternoon. Shoot a month ahead, always."),
 ])),
 ("formats", [O([("name", k), ("what", v)]) for k, v in FORMATS.items()]),
 ("format", old['format']),
 ("shareEngine", old['shareEngine']),
 ("tourCadence", O([
   ("when", "From the first event onward. Live footage exists now, so the job changes from building a "
            "world to proving it happened."),
   ("volume", "3 posts a week, down from 7. The drop is not a retreat — one post with real crowd footage "
              "outperforms four scripted ones, and the tour eats the time you were spending writing."),
   ("theThree", [
     O([("slot", "Monday · PROOF"), ("what", "Last show's best 30 seconds. Real crowd, real noise, the "
        "moment the room lost it. No narration needed — let it be loud."),
        ("why", "This is the ad. Nothing you can write beats a wide shot of 800 phones going up at once.")]),
     O([("slot", "Thursday · TRANSMISSION"), ("what", "TJ to camera, same as always — a piece of lore, a "
        "character, or the next city's story. Keeps the serial alive between shows."),
        ("why", "The voice is the brand. Losing it between tour dates costs you the thing you spent four "
                "months building.")]),
     O([("slot", "Saturday · THE ASK"), ("what", "Next city, next date, tickets. Built on a clip from the "
        "last one so the ask is evidence-led, not a poster."),
        ("why", "Announcing a date over footage of the last show converts several times better than "
                "announcing a date.")]),
   ]),
   ("reuse", "Everything in this calendar that isn't tied to the first event is evergreen — the history, "
             "the characters, the dial. A new city gets the run-up again, compressed to 6 weeks, with the "
             "proof clips from the shows you've already done cut in."),
   ("ugc", "Once there's an audience in the room, they make the PROOF slot for you. Repost with the "
           "Handler's voice over the top and it stays on-brand while costing you nothing."),
 ])),
 ("posts", posts),
])

open(OUT, 'w').write(json.dumps(doc, indent=2, ensure_ascii=False) + '\n')

rt = [p['runtimeSec'] for p in posts]
print(f'posts: {len(posts)} (days {posts[0]["day"]}–{posts[-1]["day"]})')
print(f'runtime: {min(rt)}–{max(rt)}s · mean {sum(rt)/len(rt):.0f}s')
print('all 25–60s:', all(24 <= r <= 60 for r in rt),
      '| outliers:', [(p['day'], p['runtimeSec']) for p in posts if not 24 <= p['runtimeSec'] <= 60] or 'none')
print('days contiguous:', [p['day'] for p in posts] == list(range(1, 123)))
print('distinct hooks:', len({p['hook'] for p in posts}) == len(posts))
from collections import Counter
print('formats:', dict(Counter(p['format'] for p in posts)))
print('phases :', dict(Counter(p['phase'] for p in posts)))
